// Fetches the CURRENT tasks blob from the legacy single-row table and emits
// the SQL that loads it into the new one-row-per-task table.
//
// Run this at cutover, not before — the team is actively using the live site,
// so the blob keeps changing. Run: node supabase/gen_tasks_migration.mjs
import { writeFileSync } from 'node:fs';

const URL_  = 'https://sofzlqjszuskvwlkxvhr.supabase.co';
const ANON  = process.env.SUPABASE_ANON_KEY;
if (!ANON) {
  console.error('Set SUPABASE_ANON_KEY first (the legacy anon key, still valid pre-cutover).');
  process.exit(1);
}

// qText never nulls an empty string — description is NOT NULL DEFAULT ''.
const qText = v => q(v ?? '', true);
const q = (v, keepEmpty = false) => {
  if (v === null || v === undefined || (v === '' && !keepEmpty)) return 'null';
  const s = String(v).replace(/\\/g, '\\\\').replace(/'/g, "''");
  return s.includes('\n') ? `E'${s.replace(/\n/g, '\\n')}'` : `'${s}'`;
};

const res  = await fetch(`${URL_}/rest/v1/tasks?id=eq.1&select=data`,
  { headers: { apikey: ANON, Authorization: `Bearer ${ANON}` } });
const rows  = await res.json();
const tasks = rows?.[0]?.data?.tasks ?? [];
if (!tasks.length) { console.error('No tasks found — aborting.'); process.exit(1); }

// Validate before emitting anything, so a bad row fails loudly here rather
// than halfway through a transaction in the SQL editor.
const PEOPLE = new Set(['ashar', 'rohit', 'yash']);
const problems = [];
tasks.forEach((t, i) => {
  if (!t.id)                                problems.push(`#${i} missing id`);
  if (!(t.title ?? '').trim())              problems.push(`#${i} blank title`);
  if (!PEOPLE.has(t.person))                problems.push(`#${i} unknown person "${t.person}"`);
  if (!['active', 'done'].includes(t.status)) problems.push(`#${i} bad status "${t.status}"`);
  if (t.status === 'done' && !t.completedAt) problems.push(`#${i} done but no completedAt`);
});
if (problems.length) {
  console.error('Refusing to generate — data problems:\n  ' + problems.join('\n  '));
  process.exit(1);
}

// Position: preserve existing order within each person's column.
const seen = {};
const values = tasks.map(t => {
  seen[t.person] = (seen[t.person] ?? 0) + 1;
  return `  (${q(t.person)}, ${q(t.title.trim())}, ${qText((t.description ?? '').trim())}, ` +
         `${q(t.dueDate)}::date, ${q(t.status)}, ${seen[t.person]}, ` +
         `${q(t.createdAt)}::timestamptz, ${q(t.completedAt)}::timestamptz, ${q(t.id)})`;
}).join(',\n');

const counts = Object.entries(seen).map(([p, n]) => `${p}=${n}`).join(', ');
const sql = `-- ════════════════════════════════════════════════════════════════════════════
--  Elan Internal — tasks migration  (GENERATED by supabase/gen_tasks_migration.mjs)
--  Snapshot taken ${new Date().toISOString()}
--  ${tasks.length} tasks — ${counts}
--
--  legacy_id carries the old blob's id, so re-running is a no-op rather than
--  a duplicate import.
-- ════════════════════════════════════════════════════════════════════════════

insert into public.tasks
  (person_id, title, description, due_date, status, position,
   created_at, completed_at, legacy_id)
values
${values}
on conflict (legacy_id) do nothing;
`;

writeFileSync(new URL('./04_migrate_tasks.sql', import.meta.url), sql);
console.log(`Wrote 04_migrate_tasks.sql — ${tasks.length} tasks (${counts})`);
