// Reads the mandala defaults out of the legacy data.js and emits the seed SQL
// that materialises all 81 grid positions. Run: node supabase/gen_mandala_seed.mjs
import { BLOCK_ORDER, SURROUND_KEYS, SURROUND_DISPLAY, CORE_LABEL, DEFAULTS }
  from './mandala_defaults.js';
import { writeFileSync } from 'node:fs';

// Embedded newlines are meaningful (labels wrap inside a cell), so emit
// escaped E'' strings rather than literal line breaks inside the SQL.
const q = v => {
  if (v === null || v === undefined) return 'null';
  const s = String(v).replace(/\\/g, '\\\\').replace(/'/g, "''");
  return s.includes('\n') ? `E'${s.replace(/\n/g, '\\n')}'` : `'${s}'`;
};

const rows = [];

BLOCK_ORDER.forEach((theme, blockIndex) => {
  const isCore = theme === 'CORE';
  const def    = DEFAULTS[theme];

  for (let slot = 0; slot < 9; slot++) {
    const isCenter = slot === 4;

    if (isCore) {
      if (isCenter) {
        rows.push({ blockIndex, slot, kind: 'core', blockName: 'CORE',
                    label: CORE_LABEL, owner: null, term: null, tip: '' });
      } else {
        const key = SURROUND_KEYS[slot];
        if (!key) continue;                       // never rendered
        rows.push({ blockIndex, slot, kind: 'surround', blockName: 'CORE',
                    label: SURROUND_DISPLAY[key] ?? key, owner: null, term: null, tip: '' });
      }
      continue;
    }

    if (!def) continue;

    if (isCenter) {
      rows.push({ blockIndex, slot, kind: 'center', blockName: theme,
                  label: def.center, owner: null, term: null, tip: '' });
    } else {
      // the centre is skipped when indexing into the 8-entry cells array
      const cellIndex = slot < 4 ? slot : slot - 1;
      const c = def.cells[cellIndex];
      if (!c) continue;
      rows.push({ blockIndex, slot, kind: 'cell', blockName: theme,
                  label: c.l, owner: c.o, term: c.t, tip: c.tip ?? '' });
    }
  }
});

const values = rows.map(r =>
  `  (${r.blockIndex}, ${r.slot}, ${q(r.kind)}, ${q(r.blockName)}, ` +
  `${q(r.label)}, ${q(r.owner)}, ${q(r.term)}, ${q(r.tip)}, ` +
  `${q(r.label)}, ${q(r.owner)}, ${q(r.term)}, ${q(r.tip)})`
).join(',\n');

const sql = `-- ════════════════════════════════════════════════════════════════════════════
--  Elan Internal — mandala seed  (GENERATED by supabase/gen_mandala_seed.mjs)
--
--  ${rows.length} grid positions. Seeds live values AND default_* values, so
--  "Reset to default" works without the client holding a copy of the defaults.
--  Re-running restores any cell that has NOT been edited; edited cells keep
--  their current label/owner/term/tip but get refreshed default_* columns.
-- ════════════════════════════════════════════════════════════════════════════

insert into public.mandala_cells
  (block_index, slot, kind, block_name,
   label, owner_code, term, tip,
   default_label, default_owner, default_term, default_tip)
values
${values}
on conflict (block_index, slot) do update set
  kind          = excluded.kind,
  block_name    = excluded.block_name,
  default_label = excluded.default_label,
  default_owner = excluded.default_owner,
  default_term  = excluded.default_term,
  default_tip   = excluded.default_tip;
`;

writeFileSync(new URL('./03_seed_mandala.sql', import.meta.url), sql);
console.log(`Wrote 03_seed_mandala.sql — ${rows.length} rows`);
const byKind = rows.reduce((a, r) => (a[r.kind] = (a[r.kind] ?? 0) + 1, a), {});
console.log(byKind);
